<?php
class JConfig {
	public $offline = '0';
	public $offline_message = 'Este sitio está cerrado por mantenimiento.<br /> Por favor, visítenos más tarde.';
	public $sitename = 'www.cesae.es';
	public $editor = 'tinymce';
	public $list_limit = '20';
	public $access = '1';
	public $debug = '0';
	public $debug_lang = '0';
	public $dbtype = 'mysql';
	public $host = 'localhost';
	public $user = 'cesaemysql';
	public $password = 'uo9726';
	public $db = 'cesaewebjoomla';
	public $dbprefix = 'jiutn_';
	public $live_site = '';
	public $secret = '4B7tL8qoJJnWnAkQ';
	public $gzip = '0';
	public $error_reporting = 'development';
	public $helpurl = 'http://help.joomla.org/proxy/index.php?option=com_help&amp;keyref=Help{major}{minor}:{keyref}';
	public $ftp_host = '127.0.0.1';
	public $ftp_port = '21';
	public $ftp_user = '';
	public $ftp_pass = '';
	public $ftp_root = '';
	public $ftp_enable = '0';
	public $offset = 'UTC';
	public $offset_user = 'UTC';
	public $mailer = 'mail';
	public $mailfrom = 'cesae@cesae.es';
	public $fromname = 'cesae';
	public $sendmail = '/usr/sbin/sendmail';
	public $smtpauth = '0';
	public $smtpuser = '';
	public $smtppass = '';
	public $smtphost = 'localhost';
	public $smtpsecure = 'none';
	public $smtpport = '25';
	public $caching = '1';
	public $cache_handler = 'file';
	public $cachetime = '15';
	public $MetaDesc = '';
	public $MetaKeys = '';
	public $MetaAuthor = '1';
	public $sef = '1';
	public $sef_rewrite = '1';
	public $sef_suffix = '0';
	public $unicodeslugs = '0';
	public $feed_limit = '10';
	public $log_path = '/var/www/web55/logs'; 
	public $tmp_path = '/var/www/web55/tmp';
	public $lifetime = '15';
	public $session_handler = 'database';
}
ini_set('pcre.backtrack_limit', 1150000);